// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8IxsrP3Ogm7957WSnNEr7GA-f6xoINHY',
    appId: '1:1004009100159:web:59a54d496bb051f2da404a',
    messagingSenderId: '1004009100159',
    projectId: 'photome-c5294',
    authDomain: 'photome-c5294.firebaseapp.com',
    storageBucket: 'photome-c5294.appspot.com',
    measurementId: 'G-KML1MYT9HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTe7PtIhHALMm0QxH8UxKEkQ63JxofQSc',
    appId: '1:1004009100159:android:a87613977f4ba511da404a',
    messagingSenderId: '1004009100159',
    projectId: 'photome-c5294',
    storageBucket: 'photome-c5294.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRZQ9-fQfJWkXB4tkRfHooyzhRtm3xotw',
    appId: '1:1004009100159:ios:5fcbed59a5437debda404a',
    messagingSenderId: '1004009100159',
    projectId: 'photome-c5294',
    storageBucket: 'photome-c5294.appspot.com',
    iosClientId: '1004009100159-932b9safg42sgkb9j6as43tt0r9m6vvm.apps.googleusercontent.com',
    iosBundleId: 'com.uit.photoMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRZQ9-fQfJWkXB4tkRfHooyzhRtm3xotw',
    appId: '1:1004009100159:ios:5fcbed59a5437debda404a',
    messagingSenderId: '1004009100159',
    projectId: 'photome-c5294',
    storageBucket: 'photome-c5294.appspot.com',
    iosClientId: '1004009100159-932b9safg42sgkb9j6as43tt0r9m6vvm.apps.googleusercontent.com',
    iosBundleId: 'com.uit.photoMe',
  );
}
